// <auto-generated />
using hw3webapp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace hw3webapp.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20171217205035_userWithIsActive2")]
    partial class userWithIsActive2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("hw3webapp.Models.User", b =>
                {
                    b.Property<Guid>("userID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("isActive");

                    b.Property<string>("password");

                    b.Property<string>("username");

                    b.HasKey("userID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("hw3webapp.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCompleted");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateDue");

                    b.Property<string>("Text");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
